# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param memdata.disableAnnotatedBMM 1
  set_param memdata.disableBRAMInitStrings 1
  set_param memdata.ignoreEmbeddedBMMProperties 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths /D/xilinx_workspace/aes_runner [current_fileset]

add_files /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_aes_0_0/constraints/aes_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_aes_0_bram_0/design_1_aes_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_aes_0_bram_0_1/design_1_aes_0_bram_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_1/design_1_axi_bram_ctrl_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_xbar_4/design_1_xbar_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_6/design_1_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_6/design_1_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_7/design_1_auto_ds_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_7/design_1_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_us_8/design_1_auto_us_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/ip/design_1_auto_us_8/design_1_auto_us_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /D/xilinx_workspace/aes_no_hdmi/aes_no_hdmi.data/wt [current_project]
set_property parent.project_dir /D/xilinx_workspace/aes_no_hdmi [current_project]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint design_1_wrapper.dcp
report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb
