// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1ns/1ps

module aes_s_data_in_V_if (
    // system singals
    input  wire         clk,
    input  wire         reset,
    // user signals
    input  wire [0:0]   s_data_in_V_address0,
    input  wire         s_data_in_V_ce0,
    output wire [127:0] s_data_in_V_q0,
    // bus signals
    output wire         Clk_A,
    output wire         Rst_A,
    output wire         EN_A,
    output wire [15:0]  WEN_A,
    output wire [31:0]  Addr_A,
    output wire [127:0] Dout_A,
    input  wire [127:0] Din_A
);
//------------------------Body---------------------------
assign Clk_A          = clk;
assign Rst_A          = reset;
assign EN_A           = s_data_in_V_ce0;
assign Addr_A         = {s_data_in_V_address0, 4'b0};
assign WEN_A          = 16'b0;
assign Dout_A         = 128'b0;
assign s_data_in_V_q0 = Din_A[127:0];

endmodule
