// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1ns/1ps

module aes_s_encrypted_out_V_if (
    // system singals
    input  wire         clk,
    input  wire         reset,
    // user signals
    input  wire [0:0]   s_encrypted_out_V_address1,
    input  wire         s_encrypted_out_V_ce1,
    input  wire         s_encrypted_out_V_we1,
    input  wire [127:0] s_encrypted_out_V_d1,
    // bus signals
    output wire         Clk_B,
    output wire         Rst_B,
    output wire         EN_B,
    output wire [15:0]  WEN_B,
    output wire [31:0]  Addr_B,
    output wire [127:0] Dout_B,
    input  wire [127:0] Din_B
);
//------------------------Body---------------------------
assign Clk_B  = clk;
assign Rst_B  = reset;
assign EN_B   = s_encrypted_out_V_ce1;
assign Addr_B = {s_encrypted_out_V_address1, 4'b0};
assign WEN_B  = {16{s_encrypted_out_V_we1}};
assign Dout_B = s_encrypted_out_V_d1;

endmodule
